parameters:
#    acme_helllo.example.class: Acme\HellloBundle\Example

services:
#    acme_helllo.example:
#        class: %acme_helllo.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
